### ISSUE TITLE
Switch select fields from State and City to Country and State

### ISSUE THREAD

**Issue by brashrebel** [brashrebel/wordcrash-theme#19]
I think this will be a better experience.

**Comment by d4mation** [comment]
What should it do for the States Dropdown in Countries without "States" the way that we see them? Some countries have provinces, but other, smaller countries may not bother with things like that.

**Comment by brashrebel** [comment]
I don't know. Maybe only show the state and city fields conditionally?

**Comment by d4mation** [comment]
Actually, looking at some other results for countries like India in the stored in the Database, it seems that they are filling out the fields anyway.

I think that including all three as filterable options may work best, since it filters with each one you choose anyway.

![image](https://cloud.githubusercontent.com/assets/7770631/17820385/994c1f74-661a-11e6-975d-cdf0a75d7932.png)

**Comment by brashrebel** [comment]
sure. I think the latest host in Costa Rica didn't have a state but it seems the rest do.

**Comment by d4mation** [comment]
Yuck, some Users manually entered shorthand for State names (ex. `MI`) while others haven't. 

I already have written some Regex to standardize just about any name for the United States into "USA" for the Host Cards and to "United States of America" for the Country selection, but standardizing the rest of that will be quite the nasty little Switch/Conditional I do believe...

Otherwise results for "MI" and "Michigan" would be separate.

**Comment by brashrebel** [comment]
Yeah, what we need to do is make the input field on the form a select instead of a text I think. To standardize results. Then just manually update the values for these current hosts.

**Comment by d4mation** [comment]
If we make it a Select rather than an Input that would unintentionally alienate Users outside of the US I think.

What we could do is run a Filter on the Submission Process to Sanitize those values on Save. Run one on Country as well as State. Much better than trying to fix it up on the Front-end.

Check against common abbreviations for States and Countries and go from there. Some will slip through, but we'll get most of them.

**Comment by d4mation** [comment]
[I have these changes up on the Staging Site.](http://wordcrash.staging.wpengine.com/)

I opened an Issue at #20 about fixing the State Abbreviations problem.
